apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-web
  template:
    metadata:
      labels:
        app: dev-web
    spec:
      containers:
      - name: web
        image: simple-static-web:1.0.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: prd-html   # use prod-html for prod deployment
