apiVersion: apps/v1
kind: Deployment
metadata:
  name: prd-web
  namespace: prd-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-web
  template:
    metadata:
      labels:
        app: prd-web
    spec:
      containers:
      - name: prd-web
        image: simple-static-web:1.0.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: prd-html  
