apiVersion: apps/v1
kind: Deployment
metadata:
  name: prd-web
  namespace: dev-web 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-web
  template:
    metadata:
      labels:
        app: prd-web
    spec:
      containers:
      - name: prd-web
        image: simple-static-web:1.0.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: html
          mountPath: /usr/share/nginx/html
        - name: auth
          mountPath: /etc/nginx/auth/auth
          subPath: auth
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: prd-nginx-config
      - name: html
        configMap:
          name: prd-html
      - name: auth
        secret:
          secretName: basic-auth-secret-prd
