apiVersion: v1
kind: ConfigMap
metadata:
  name: prd-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <title>Prod Web</title>
      <style>
        body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
      </style>
    </head>
    <body>
      <h1>Hello from Prod Environment!</h1>
      <p>This is the prod static web page.</p>
    </body>
    </html>
