apiVersion: v1
kind: Service
metadata:
  name: simple-static-web-prd-svc
  namespace: prd-web
spec:
  selector:
    app: prd-web
  type: ClusterIP  # or LoadBalancer if your environment supports it
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
