apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <title>Welcome to DEV Rancher Static Web</title>
      <style>
        body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
      </style>
    </head>
    <body>
      <h1>Hello from DEV Rancher!</h1>
      <p>This is your simple static web server deployed on Kubernetes.</p>
    </body>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dev-html
