apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ngnix-secret.yaml
  - dev-nginx-config.yaml
  - dev-html-configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
