apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-login-ingress
  namespace: node-web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ol9-admin-01.nip.io
      http:
        paths:
          - path: /node
            pathType: Prefix
            backend:
              service:
                name: node-login-svc
                port:
                  number: 80
